[2023-07-08T11:02:25.898+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: assignment.get_departed_flights_from_cdg manual__2023-07-08T11:02:24.805171+00:00 [queued]>
[2023-07-08T11:02:25.910+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: assignment.get_departed_flights_from_cdg manual__2023-07-08T11:02:24.805171+00:00 [queued]>
[2023-07-08T11:02:25.910+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-08T11:02:25.931+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): get_departed_flights_from_cdg> on 2023-07-08 11:02:24.805171+00:00
[2023-07-08T11:02:25.939+0000] {standard_task_runner.py:57} INFO - Started process 454 to run task
[2023-07-08T11:02:25.942+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'get_departed_flights_from_cdg', 'manual__2023-07-08T11:02:24.805171+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp1th8lyqy']
[2023-07-08T11:02:25.943+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask get_departed_flights_from_cdg
[2023-07-08T11:02:26.008+0000] {task_command.py:410} INFO - Running <TaskInstance: assignment.get_departed_flights_from_cdg manual__2023-07-08T11:02:24.805171+00:00 [running]> on host da250f106141
[2023-07-08T11:02:26.146+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='assignment' AIRFLOW_CTX_TASK_ID='get_departed_flights_from_cdg' AIRFLOW_CTX_EXECUTION_DATE='2023-07-08T11:02:24.805171+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-08T11:02:24.805171+00:00'
[2023-07-08T11:02:26.538+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 71, in get_departed_flights_from_cdg
    departure = FlightData.from_json(json_flight)
NameError: name 'json_flight' is not defined
[2023-07-08T11:02:26.550+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=assignment, task_id=get_departed_flights_from_cdg, execution_date=20230708T110224, start_date=20230708T110225, end_date=20230708T110226
[2023-07-08T11:02:26.572+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 53 for task get_departed_flights_from_cdg (name 'json_flight' is not defined; 454)
[2023-07-08T11:02:26.597+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T11:02:26.646+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
